### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by xbec65** [canbeardig/MinimalistFox#1]
Hi,

I love these theme in Firefox. I have a request, is it possible to make these theme in Vivaldi browser theme editor? I tried the color code, but not feeling the same.

Thanks.

**Comment by canbeardig** [comment]
I have checked the Vivaldi customization options but compared to Firefox it seems that they are limited. Still, for **green tabs theme** you can try these options and follow the same pattern for other colour schemes:

### Colours:
- Background: #282828
- Foreground: #aaaaaa
- Highlight: #aaaaaa
- Accent: #689d69
- "Accent from page" and "Accent on window" disabled.
- "Fade foreground colours" disabled.
- Contrast=0
- Limit Accent colour saturation=%100

### Background:
- Type: Colour
- Custom colour: #282828

### Settings:
- Blur=0
- Transparency=0%
- Corner rounding=5
- "Transparent tab bar" and "Transparent background tabs" disabled.
- "Use simple scrollbars" enabled.

**Comment by xbec65** [comment]
Thanks man, I will try that.
